services:
  - type: web
    name: telegram-download-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PLATFORM
        sync: false
      - key: BOT_TOKEN
        sync: false
